name: Deploy to s3

on:
  push:
    branches: [ "main" ]

jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: eu-central-1

    steps:
      
      - uses: actions/checkout@v3

      - name: Upload index to s3
        run: aws s3 cp index.html s3://droggelbecher-task-github  
